export const bikeRentAdminSidebarMenu = [
  {
    type: "section",
    title: "Main Menu",
    permissionKey: "main",
    items: [
      {
        type: "link",
        label: "Dashboard",
        icon: "LayoutDashboard",
        path: "/admin/bike-rent/dashboard",
        permissionKey: "dashboard",
      },
    ],
  },
  {
    type: "section",
    title: "Vendors",
    permissionKey: "vendors",
    items: [
      {
        type: "link",
        label: "Vendor List",
        icon: "Building2",
        path: "/admin/bike-rent/vendors",
        permissionKey: "list",
      },
      {
        type: "link",
        label: "Joining Requests",
        icon: "UserPlus",
        path: "/admin/bike-rent/joining-requests",
        permissionKey: "joining_requests",
      },
      {
        type: "link",
        label: "Category Approvals",
        icon: "FolderTree",
        path: "/admin/bike-rent/category-approvals",
        permissionKey: "joining_requests",
      },
      {
        type: "link",
        label: "Bike Approvals",
        icon: "Bike",
        path: "/admin/bike-rent/bike-approvals",
        permissionKey: "joining_requests",
      },
      {
        type: "link",
        label: "Coupon Approvals",
        icon: "Tag",
        path: "/admin/bike-rent/coupon-approvals",
        permissionKey: "joining_requests",
      },
      {
        type: "link",
        label: "Vendor Withdrawals",
        icon: "Wallet",
        path: "/admin/bike-rent/vendor-withdrawals",
        permissionKey: "joining_requests",
      },
    ],
  },
  {
    type: "section",
    title: "Inventory",
    permissionKey: "inventory",
    items: [
      {
        type: "link",
        label: "Bike Rent Zones",
        icon: "MapPin",
        path: "/admin/bike-rent/zones",
        permissionKey: "zones",
      },
      {
        type: "link",
        label: "Bike Categories",
        icon: "FolderTree",
        path: "/admin/bike-rent/categories",
        permissionKey: "categories",
      },
      {
        type: "link",
        label: "Bike Management",
        icon: "Bike",
        path: "/admin/bike-rent/bikes",
        permissionKey: "bikes",
      },
    ],
  },
  {
    type: "section",
    title: "Bookings",
    permissionKey: "bookings",
    items: [
      {
        type: "link",
        label: "Live Rentals",
        icon: "Bike",
        path: "/admin/bike-rent/bookings?ops=live",
        permissionKey: "list",
      },
      {
        type: "link",
        label: "Upcoming Pickups",
        icon: "Clock",
        path: "/admin/bike-rent/bookings?ops=pickups",
        permissionKey: "list",
      },
      {
        type: "link",
        label: "Upcoming Returns",
        icon: "RefreshCw",
        path: "/admin/bike-rent/bookings?ops=returns",
        permissionKey: "list",
      },
      {
        type: "link",
        label: "Late Returns",
        icon: "AlertTriangle",
        path: "/admin/bike-rent/bookings?ops=late",
        permissionKey: "list",
      },
      {
        type: "link",
        label: "Extension Requests",
        icon: "Timer",
        path: "/admin/bike-rent/bookings?ops=extensions",
        permissionKey: "list",
      },
      {
        type: "link",
        label: "Pending Deposits",
        icon: "PiggyBank",
        path: "/admin/bike-rent/bookings?depositStatus=pending_collection",
        permissionKey: "list",
      },
      {
        type: "link",
        label: "Pending Approvals",
        icon: "Clock",
        path: "/admin/bike-rent/bookings?status=pending_approval",
        permissionKey: "list",
      },
      {
        type: "link",
        label: "Fleet Timeline",
        icon: "Calendar",
        path: "/admin/bike-rent/fleet-timeline",
        permissionKey: "list",
      },
      {
        type: "link",
        label: "Bike Inspections",
        icon: "ClipboardCheck",
        path: "/admin/bike-rent/inspections",
        permissionKey: "list",
      },
      {
        type: "link",
        label: "All Bookings",
        icon: "ClipboardList",
        path: "/admin/bike-rent/bookings",
        permissionKey: "list",
      },
    ],
  },
  {
    type: "section",
    title: "Customers",
    permissionKey: "customers",
    items: [
      {
        type: "link",
        label: "Customers",
        icon: "Users",
        path: "/admin/bike-rent/customers",
        permissionKey: "list",
      },
    ],
  },
  {
    type: "section",
    title: "Operations",
    permissionKey: "operations",
    items: [
      {
        type: "link",
        label: "Reports",
        icon: "FileText",
        path: "/admin/bike-rent/reports",
        permissionKey: "reports",
      },
      {
        type: "link",
        label: "Wallet & Refunds",
        icon: "Wallet",
        path: "/admin/bike-rent/wallet",
        permissionKey: "reports",
      },
      {
        type: "link",
        label: "Coupons",
        icon: "Ticket",
        path: "/admin/bike-rent/coupons",
        permissionKey: "coupons",
      },
      {
        type: "link",
        label: "Finance",
        icon: "PiggyBank",
        path: "/admin/bike-rent/finance",
        permissionKey: "reports",
      },
      {
        type: "link",
        label: "Settlements",
        icon: "IndianRupee",
        path: "/admin/bike-rent/settlements",
        permissionKey: "reports",
      },
      {
        type: "link",
        label: "Tax & Billing",
        icon: "Receipt",
        path: "/admin/bike-rent/tax-billing",
        permissionKey: "settings",
      },
      {
        type: "link",
        label: "Settings",
        icon: "Settings",
        path: "/admin/bike-rent/settings",
        permissionKey: "settings",
      },
    ],
  },
];
